Correct indent `if`s

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -32,14 +32,14 @@ cd "$ROOT/$1" || { echo "$ROOT/$1 doesn't exist, aborting"; exit 1; }
 
 for I in docs conf; do
 	if [ -x "./$I/deploy/init" ]; then
-	./$I/deploy/init
-	RET_VAL=$?
-	if [ ! $RET_VAL -eq 0 ]; then
-		echo "$I/deploy/init returned error $RET_VAL, exiting"
-		exit
-	fi
+		./$I/deploy/init
+		RET_VAL=$?
+		if [ ! $RET_VAL -eq 0 ]; then
+			echo "$I/deploy/init returned error $RET_VAL, exiting"
+			exit
+		fi
 	elif [ -f "./$I/deploy/init" ]; then
-	echo "$I/deploy/init exists but it's not executable, skipping"
+		echo "$I/deploy/init exists but it's not executable, skipping"
 	fi
 done
 
@@ -67,28 +67,28 @@ if [ -f "$COMPOSER_JSON" ]; then
 	PHPSTAN="phpstan/phpstan"
 	PHPSTAN_BOOTSTRAP="${VENDOR_DIR}/${PHPSTAN}/bootstrap.php"
 	if [ -z "$DEV_DEPS" ]; then
-	echo "${GRAY}No dev dependencies found in $INSTALLED_PHP${NORMAL}"
+		echo "${GRAY}No dev dependencies found in $INSTALLED_PHP${NORMAL}"
 	else
-	echo "${BOLD}Removing dev dependencies${NORMAL}"
-	shopt -s dotglob
-	for DEP in $DEV_DEPS; do
-		if [ ! -d "./$VENDOR_DIR/$DEP" ]; then
-		continue
-		fi
-		RECREATE_PHPSTAN_BOOTSTRAP=0
-		if [ "$DEP" = "$PHPSTAN" ] && [ -f "$PHPSTAN_BOOTSTRAP" ]; then
-		RECREATE_PHPSTAN_BOOTSTRAP=1
-		fi
-		rm -rf "./$VENDOR_DIR/$DEP"/*
-		echo "Removed by $0" > "./$VENDOR_DIR/$DEP/REMOVED-BY-DEPLOY"
-		echo "├ $DEP removed"
-		if [ $RECREATE_PHPSTAN_BOOTSTRAP -eq 1 ]; then
-		echo "<?php // $PHPSTAN_BOOTSTRAP re-created empty by $0, required by composer/autoload_files.php" > $PHPSTAN_BOOTSTRAP
-		echo "│ └ ${GRAY}$PHPSTAN_BOOTSTRAP re-created, required by composer/autoload_files.php${NORMAL}"
-		fi
-	done
-	echo "└ ${BOLD}Done${NORMAL}"
-	shopt -u dotglob
+		echo "${BOLD}Removing dev dependencies${NORMAL}"
+		shopt -s dotglob
+		for DEP in $DEV_DEPS; do
+			if [ ! -d "./$VENDOR_DIR/$DEP" ]; then
+				continue
+			fi
+			RECREATE_PHPSTAN_BOOTSTRAP=0
+			if [ "$DEP" = "$PHPSTAN" ] && [ -f "$PHPSTAN_BOOTSTRAP" ]; then
+				RECREATE_PHPSTAN_BOOTSTRAP=1
+			fi
+			rm -rf "./$VENDOR_DIR/$DEP"/*
+			echo "Removed by $0" > "./$VENDOR_DIR/$DEP/REMOVED-BY-DEPLOY"
+			echo "├ $DEP removed"
+			if [ $RECREATE_PHPSTAN_BOOTSTRAP -eq 1 ]; then
+				echo "<?php // $PHPSTAN_BOOTSTRAP re-created empty by $0, required by composer/autoload_files.php" > $PHPSTAN_BOOTSTRAP
+				echo "│ └ ${GRAY}$PHPSTAN_BOOTSTRAP re-created, required by composer/autoload_files.php${NORMAL}"
+			fi
+		done
+		echo "└ ${BOLD}Done${NORMAL}"
+		shopt -u dotglob
 	fi
 else
 	echo "${GRAY}Not removing dev dependencies, $COMPOSER_JSON not found${NORMAL}"
