Use real tabs instead of some half-tabs

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -9,14 +9,14 @@ VENDOR_IGNORE=$VENDOR_DIR/.gitignore
 CACHE_DIR=$SITE_DIR/temp/cache
 
 if [ $# -eq 0 ]; then
-    echo "$0 <site>, where site is:"
-    ls -1 $ROOT
-    exit 1
+	echo "$0 <site>, where site is:"
+	ls -1 $ROOT
+	exit 1
 fi
 
 if [ ! -d "$ROOT/$1" ]; then
-    echo "Site $1 doesn't exist"
-    exit 2
+	echo "Site $1 doesn't exist"
+	exit 2
 fi
 
 BOLD=$(tput bold)
@@ -30,16 +30,16 @@ echo "${BOLD}Deploying ${GREEN}$1${NORMAL}"
 cd $ROOT/$1
 
 for I in docs conf; do
-    if [ -x "./$I/deploy/init" ]; then
+	if [ -x "./$I/deploy/init" ]; then
 	./$I/deploy/init
 	RET_VAL=$?
 	if [ ! $RET_VAL -eq 0 ]; then
-	    echo "$I/deploy/init returned error $RET_VAL, exiting"
-	    exit
+		echo "$I/deploy/init returned error $RET_VAL, exiting"
+		exit
 	fi
-    elif [ -f "./$I/deploy/init" ]; then
+	elif [ -f "./$I/deploy/init" ]; then
 	echo "$I/deploy/init exists but it's not executable, skipping"
-    fi
+	fi
 done
 
 export GIT_SSH_KEY=$HOME/.ssh/web-$1.key
@@ -49,47 +49,47 @@ git reset origin/master --hard
 git submodule update --init --recursive
 
 if [ -f "$COMPOSER_LOCK" ] && [ -f "$VENDOR_IGNORE" ]; then
-    cd $SITE_DIR
-    composer install --no-dev
-    echo "${BOLD}Composer dependencies installed${NORMAL}"
-    cd - > /dev/null
+	cd $SITE_DIR
+	composer install --no-dev
+	echo "${BOLD}Composer dependencies installed${NORMAL}"
+	cd - > /dev/null
 fi
 
 if [ -d "$CACHE_DIR" ]; then
-    sudo rm -r $CACHE_DIR
-    echo "${BOLD}Cache purged${NORMAL}"
+	sudo rm -r $CACHE_DIR
+	echo "${BOLD}Cache purged${NORMAL}"
 fi
 
 if [ -f "$COMPOSER_JSON" ]; then
-    DEV_DEPS=$(jq --raw-output '."require-dev" | keys[]' $COMPOSER_JSON)
-    PHPSTAN="phpstan/phpstan"
-    PHPSTAN_BOOTSTRAP="${VENDOR_DIR}/${PHPSTAN}/bootstrap.php"
-    if [ $? -ne 0 ]; then
+	DEV_DEPS=$(jq --raw-output '."require-dev" | keys[]' $COMPOSER_JSON)
+	PHPSTAN="phpstan/phpstan"
+	PHPSTAN_BOOTSTRAP="${VENDOR_DIR}/${PHPSTAN}/bootstrap.php"
+	if [ $? -ne 0 ]; then
 	echo "${GRAY}No dev dependencies found in $COMPOSER_JSON${NORMAL}"
-    else
+	else
 	echo "${BOLD}Removing dev dependencies${NORMAL}"
 	shopt -s dotglob
 	for DEP in $DEV_DEPS; do
-	    if [ ! -d "./$VENDOR_DIR/$DEP" ]; then
+		if [ ! -d "./$VENDOR_DIR/$DEP" ]; then
 		continue
-	    fi
-	    RECREATE_PHPSTAN_BOOTSTRAP=0
-	    if [ "$DEP" = "$PHPSTAN" ] && [ -f "$PHPSTAN_BOOTSTRAP" ]; then
+		fi
+		RECREATE_PHPSTAN_BOOTSTRAP=0
+		if [ "$DEP" = "$PHPSTAN" ] && [ -f "$PHPSTAN_BOOTSTRAP" ]; then
 		RECREATE_PHPSTAN_BOOTSTRAP=1
-	    fi
-	    rm -rf ./$VENDOR_DIR/$DEP/*
-	    echo "Removed by $0" > ./$VENDOR_DIR/$DEP/REMOVED-BY-DEPLOY
-	    echo "├ $DEP removed"
-	    if [ $RECREATE_PHPSTAN_BOOTSTRAP -eq 1 ]; then
+		fi
+		rm -rf ./$VENDOR_DIR/$DEP/*
+		echo "Removed by $0" > ./$VENDOR_DIR/$DEP/REMOVED-BY-DEPLOY
+		echo "├ $DEP removed"
+		if [ $RECREATE_PHPSTAN_BOOTSTRAP -eq 1 ]; then
 		echo "<?php // $PHPSTAN_BOOTSTRAP re-created empty by $0, required by composer/autoload_files.php" > $PHPSTAN_BOOTSTRAP
 		echo "│ └ ${GRAY}$PHPSTAN_BOOTSTRAP re-created, required by composer/autoload_files.php${NORMAL}"
-	    fi
+		fi
 	done
 	echo "└ ${BOLD}Done${NORMAL}"
 	shopt -u dotglob
-    fi
+	fi
 else
-    echo "${GRAY}Not removing dev dependencies, $COMPOSER_JSON not found${NORMAL}"
+	echo "${GRAY}Not removing dev dependencies, $COMPOSER_JSON not found${NORMAL}"
 fi
 
 
