Resolve some shellcheck warnings

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -28,7 +28,7 @@ NORMAL=$(tput sgr0)
 
 echo "${BOLD}Deploying ${GREEN}$1${NORMAL}"
 
-cd $ROOT/$1
+cd "$ROOT/$1" || { echo "$ROOT/$1 doesn't exist, aborting"; exit 1; }
 
 for I in docs conf; do
 	if [ -x "./$I/deploy/init" ]; then
@@ -50,10 +50,11 @@ git reset origin/master --hard
 git submodule update --init --recursive
 
 if [ -f "$COMPOSER_LOCK" ] && [ -f "$VENDOR_IGNORE" ]; then
-	cd $SITE_DIR
+	CURRENT_DIR=$(pwd)
+	cd $SITE_DIR || { echo "$SITE_DIR doesn't exist, aborting"; exit 1; }
 	composer install --no-dev
 	echo "${BOLD}Composer dependencies installed${NORMAL}"
-	cd - > /dev/null
+	cd "$CURRENT_DIR" || { echo "$CURRENT_DIR doesn't exist anymore?"; exit 1; }
 fi
 
 if [ -d "$CACHE_DIR" ]; then
@@ -62,10 +63,10 @@ if [ -d "$CACHE_DIR" ]; then
 fi
 
 if [ -f "$COMPOSER_JSON" ]; then
-	DEV_DEPS=$(php -r 'foreach ((require "'$INSTALLED_PHP'")["versions"] as $k => $v) if ($v["dev_requirement"]) $deps[] = $k; echo implode(PHP_EOL, $deps); exit((int)empty($deps));')
+	DEV_DEPS=$(php -r '$deps = []; foreach ((require "'$INSTALLED_PHP'")["versions"] as $k => $v) if ($v["dev_requirement"]) $deps[] = $k; echo implode(PHP_EOL, $deps);')
 	PHPSTAN="phpstan/phpstan"
 	PHPSTAN_BOOTSTRAP="${VENDOR_DIR}/${PHPSTAN}/bootstrap.php"
-	if [ $? -ne 0 ]; then
+	if [ -z "$DEV_DEPS" ]; then
 	echo "${GRAY}No dev dependencies found in $INSTALLED_PHP${NORMAL}"
 	else
 	echo "${BOLD}Removing dev dependencies${NORMAL}"
@@ -78,8 +79,8 @@ if [ -f "$COMPOSER_JSON" ]; then
 		if [ "$DEP" = "$PHPSTAN" ] && [ -f "$PHPSTAN_BOOTSTRAP" ]; then
 		RECREATE_PHPSTAN_BOOTSTRAP=1
 		fi
-		rm -rf ./$VENDOR_DIR/$DEP/*
-		echo "Removed by $0" > ./$VENDOR_DIR/$DEP/REMOVED-BY-DEPLOY
+		rm -rf "./$VENDOR_DIR/$DEP"/*
+		echo "Removed by $0" > "./$VENDOR_DIR/$DEP/REMOVED-BY-DEPLOY"
 		echo "├ $DEP removed"
 		if [ $RECREATE_PHPSTAN_BOOTSTRAP -eq 1 ]; then
 		echo "<?php // $PHPSTAN_BOOTSTRAP re-created empty by $0, required by composer/autoload_files.php" > $PHPSTAN_BOOTSTRAP
@@ -100,6 +101,6 @@ curl \
 --output /dev/null \
 --user-agent "Deploy McDeploymentface" \
 --write-out "%{url_effective} -> HTTP %{http_code} (in %{time_total}s)\n" \
-$1 | sed "s/\(HTTP 2[0-9]\+\)/${BOLD}${GREEN}\\1${NORMAL}/" | sed "s/\(HTTP 5[0-9]\+\)/${BOLD}${RED}\\1 FAILURE${NORMAL}/"
+"$1" | sed "s/\(HTTP 2[0-9]\+\)/${BOLD}${GREEN}\\1${NORMAL}/" | sed "s/\(HTTP 5[0-9]\+\)/${BOLD}${RED}\\1 FAILURE${NORMAL}/"
 
 echo "${BOLD}${GREEN}$1 successfully deployed${NORMAL}"
